### ISSUE TITLE
`dist` directory not included in the npm package

### ISSUE THREAD

**Issue by honey32** [mizdra/happy-css-modules#266]
version: 3.1.0 

reference: https://www.npmjs.com/package/happy-css-modules/v/3.1.0?activeTab=code

has `bin` and `src`, but `dist` is missing.

---

Thank you for this tools improving experience of development a lot.

**Comment by mizdra** [comment]
Oh... I will fix it today!

**Comment by mizdra** [comment]
I shipped `happy-css-modules@3.1.1`. Please try it out! @honey32 

https://github.com/mizdra/happy-css-modules/releases/tag/v3.1.1

**Comment by honey32** [comment]
Worked in my project! Thank you!
